name: student_progress_monitor_app
description: An app for teachers to monitor students progress in class.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.1.0
  go_router: ^13.2.2
  fl_chart: ^0.67.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.4
  flutter_secure_storage: ^9.0.0
  chopper: ^7.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  multi_dropdown: ^2.1.4
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  chopper_generator: ^7.4.0
  freezed: ^2.5.0
  json_serializable: ^6.7.1

  flutter_launcher_icons: ^0.13.1

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  adaptive_icon_background: "#15803D"
  adaptive_icon_foreground: "assets/icon_fg.png"
  ios: true
  remove_alpha_ios: true
